<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.12.0 on darwin)" generated="20250123 15:27:25.945" rpa="false" schemaversion="4">
<suite id="s1" name="HomeSuite" source="/Users/muhammad.anggadirja/Documents/kardoos/TestSuite/HomeSuite.robot">
<kw name="Begin Web Test" library="dev" type="SETUP">
<kw name="Remove Files" library="OperatingSystem">
<arg>/Users/muhammad.anggadirja/Documents/kardoos/report/*.png</arg>
<doc>Uses `Remove File` to remove multiple files one-by-one.</doc>
<msg timestamp="20250123 15:27:26.501" level="INFO" html="true">File '&lt;a href="file:///Users/muhammad.anggadirja/Documents/kardoos/report/*.png"&gt;/Users/muhammad.anggadirja/Documents/kardoos/report/*.png&lt;/a&gt;' does not exist.</msg>
<status status="PASS" starttime="20250123 15:27:26.500" endtime="20250123 15:27:26.501"/>
</kw>
<kw name="Open Browser" library="SeleniumLibrary">
<arg>about:blank</arg>
<arg>${BROWSER}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20250123 15:27:26.502" level="INFO">Opening browser 'chrome' to base url 'about:blank'.</msg>
<status status="PASS" starttime="20250123 15:27:26.501" endtime="20250123 15:27:29.590"/>
</kw>
<kw name="Set Window Size" library="SeleniumLibrary">
<arg>430</arg>
<arg>932</arg>
<doc>Sets current windows size to given ``width`` and ``height``.</doc>
<status status="PASS" starttime="20250123 15:27:29.591" endtime="20250123 15:27:29.954"/>
</kw>
<kw name="Go To" library="SeleniumLibrary">
<arg>${KARDOOS_URL}</arg>
<doc>Navigates the current browser window to the provided ``url``.</doc>
<msg timestamp="20250123 15:27:29.955" level="INFO">Opening url 'https://dev.kardoos.co.id/'</msg>
<status status="PASS" starttime="20250123 15:27:29.954" endtime="20250123 15:27:31.017"/>
</kw>
<status status="PASS" starttime="20250123 15:27:26.500" endtime="20250123 15:27:31.017"/>
</kw>
<test id="s1-t1" name="verify user can access design page from header" line="11">
<kw name="Login to kardoos" library="LoginTest" type="SETUP">
<kw name="Given user is on home page" library="HomePage">
<kw name="Run Keyword And Return Status" library="BuiltIn">
<var>${isMenuInstantDisplayed}</var>
<arg>Wait Until Element Is Visible</arg>
<arg>${textMenuInstant}</arg>
<doc>Runs the given keyword with given arguments and returns the status as a Boolean value.</doc>
<kw name="Wait Until Element Is Visible" library="SeleniumLibrary">
<arg>${textMenuInstant}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<msg timestamp="20250123 15:27:41.719" level="INFO" html="true">&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan="3"&gt;&lt;a href="selenium-screenshot-1.png"&gt;&lt;img src="selenium-screenshot-1.png" width="800px"&gt;&lt;/a&gt;</msg>
<msg timestamp="20250123 15:27:41.720" level="FAIL">Element 'xpath=//ul[@class='header-menu-list']/li/a[text()='Instant']' not visible after 10 seconds.</msg>
<status status="FAIL" starttime="20250123 15:27:31.042" endtime="20250123 15:27:41.730"/>
</kw>
<msg timestamp="20250123 15:27:41.730" level="INFO">${isMenuInstantDisplayed} = False</msg>
<status status="PASS" starttime="20250123 15:27:31.039" endtime="20250123 15:27:41.730"/>
</kw>
<kw name="Run Keyword If" library="BuiltIn">
<arg>'${isMenuInstantDisplayed}' == 'False'</arg>
<arg>Go To</arg>
<arg>${KARDOOS_URL}</arg>
<arg>ELSE</arg>
<arg>Log To Console</arg>
<arg>instant menu displayed</arg>
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<kw name="Go To" library="SeleniumLibrary">
<arg>${KARDOOS_URL}</arg>
<doc>Navigates the current browser window to the provided ``url``.</doc>
<msg timestamp="20250123 15:27:41.731" level="INFO">Opening url 'https://dev.kardoos.co.id/'</msg>
<status status="PASS" starttime="20250123 15:27:41.731" endtime="20250123 15:27:42.187"/>
</kw>
<status status="PASS" starttime="20250123 15:27:41.730" endtime="20250123 15:27:42.187"/>
</kw>
<kw name="Wait Until Element Is Visible" library="SeleniumLibrary">
<arg>${textMenuInstant}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<msg timestamp="20250123 15:27:49.314" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(54, 'Connection reset by peer')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.318" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ace60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.322" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084acbf0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.324" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ac920&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:42.187" endtime="20250123 15:27:49.324"/>
</kw>
<kw name="Element Should Be Visible" library="SeleniumLibrary">
<arg>${textMenuInstant}</arg>
<doc>Verifies that the element identified by ``locator`` is visible.</doc>
<status status="NOT RUN" starttime="20250123 15:27:49.324" endtime="20250123 15:27:49.324"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:31.039" endtime="20250123 15:27:49.324"/>
</kw>
<kw name="When user go to login page" library="HomePage">
<status status="NOT RUN" starttime="20250123 15:27:49.325" endtime="20250123 15:27:49.325"/>
</kw>
<kw name="Then user is on login page" library="LoginPage">
<status status="NOT RUN" starttime="20250123 15:27:49.325" endtime="20250123 15:27:49.325"/>
</kw>
<kw name="When user input credential for login" library="LoginPage">
<status status="NOT RUN" starttime="20250123 15:27:49.325" endtime="20250123 15:27:49.326"/>
</kw>
<kw name="And user click button masuk for login" library="LoginPage">
<status status="NOT RUN" starttime="20250123 15:27:49.326" endtime="20250123 15:27:49.326"/>
</kw>
<kw name="Then user success to login" library="HomePage">
<status status="NOT RUN" starttime="20250123 15:27:49.326" endtime="20250123 15:27:49.326"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:31.022" endtime="20250123 15:27:49.326"/>
</kw>
<kw name="Logout from kardoos" library="LoginTest" type="TEARDOWN">
<kw name="When user reload page" library="HomePage">
<kw name="Go To" library="SeleniumLibrary">
<arg>${KARDOOS_URL}</arg>
<doc>Navigates the current browser window to the provided ``url``.</doc>
<msg timestamp="20250123 15:27:49.329" level="INFO">Opening url 'https://dev.kardoos.co.id/'</msg>
<msg timestamp="20250123 15:27:49.332" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084adf40&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/url</msg>
<msg timestamp="20250123 15:27:49.334" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845fad0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/url</msg>
<msg timestamp="20250123 15:27:49.337" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845ffe0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/url</msg>
<msg timestamp="20250123 15:27:49.342" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1083f70b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.345" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1082184d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.349" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845f0e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.357" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845fbc0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.358" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/url (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1083666c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.328" endtime="20250123 15:27:49.386"/>
</kw>
<kw name="Reload Page" library="SeleniumLibrary">
<doc>Simulates user reloading page.</doc>
<msg timestamp="20250123 15:27:49.388" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084acb60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh</msg>
<msg timestamp="20250123 15:27:49.389" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084acd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh</msg>
<msg timestamp="20250123 15:27:49.390" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ac6e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh</msg>
<msg timestamp="20250123 15:27:49.392" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae660&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.393" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae870&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.395" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084aea80&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.397" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1082184d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.397" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae360&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.386" endtime="20250123 15:27:49.401"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:49.327" endtime="20250123 15:27:49.401"/>
</kw>
<kw name="And user click button logout" library="HomePage">
<kw name="Wait Until Element Is Visible" library="SeleniumLibrary">
<arg>${buttonLogout}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<msg timestamp="20250123 15:27:49.404" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af3e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.406" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084aeea0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.407" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af170&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.410" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afa40&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.411" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afc50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.412" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afe60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.413" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085740b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.434" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af770&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.402" endtime="20250123 15:27:49.440"/>
</kw>
<kw name="Scroll Element Into View" library="SeleniumLibrary">
<arg>${buttonLogout}</arg>
<doc>Scrolls the element identified by ``locator`` into view.</doc>
<msg timestamp="20250123 15:27:49.442" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574950&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.444" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574290&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.445" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afb90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.447" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1080e20f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.448" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085740b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.449" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574530&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.451" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085749e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.451" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.441" endtime="20250123 15:27:49.457"/>
</kw>
<kw name="Click Element" library="SeleniumLibrary">
<arg>${buttonLogout}</arg>
<doc>Click the element identified by ``locator``.</doc>
<msg timestamp="20250123 15:27:49.458" level="INFO">Clicking element 'xpath=//div[@class='tab-login-menu']/div[6]'.</msg>
<msg timestamp="20250123 15:27:49.459" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.461" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575580&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.462" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575880&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.464" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085761b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.465" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085763f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.467" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576630&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.468" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1082184d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.469" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575e20&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.458" endtime="20250123 15:27:49.472"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:49.401" endtime="20250123 15:27:49.472"/>
</kw>
<kw name="And user confirm to logout" library="HomePage">
<kw name="Wait Until Element Is Visible" library="SeleniumLibrary">
<arg>${buttonConfirmLogout}</arg>
<doc>Waits until the element ``locator`` is visible.</doc>
<msg timestamp="20250123 15:27:49.475" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085771d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.477" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ac920&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.478" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574b00&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.480" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576d50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.481" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085773e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.482" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577620&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.483" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577860&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.483" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574110&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.473" endtime="20250123 15:27:49.487"/>
</kw>
<kw name="Click Element" library="SeleniumLibrary">
<arg>${buttonConfirmLogout}</arg>
<doc>Click the element identified by ``locator``.</doc>
<msg timestamp="20250123 15:27:49.488" level="INFO">Clicking element 'xpath=//div[text()='Keluar Akun']/following-sibling::div/button[text()='Iya']'.</msg>
<msg timestamp="20250123 15:27:49.490" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c8080&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.491" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084aee10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.492" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085777a0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.495" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576900&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.496" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c8260&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.497" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c84a0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.498" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c86e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.498" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577590&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.487" endtime="20250123 15:27:49.502"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:49.472" endtime="20250123 15:27:49.503"/>
</kw>
<kw name="Then user success to logout" library="HomePage">
<kw name="Wait Until Element Is Not Visible" library="SeleniumLibrary">
<arg>${iconProfile}</arg>
<doc>Waits until the element ``locator`` is not visible.</doc>
<msg timestamp="20250123 15:27:49.505" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c97c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.506" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9550&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.508" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9280&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.510" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9e50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.536" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577ec0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.537" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577b60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.538" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576900&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.538" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9b20&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.503" endtime="20250123 15:27:49.541"/>
</kw>
<kw name="Element Should Not Be Visible" library="SeleniumLibrary">
<arg>${iconProfile}</arg>
<doc>Verifies that the element identified by ``locator`` is NOT visible.</doc>
<msg timestamp="20250123 15:27:49.543" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca3f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.544" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca270&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.545" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9f10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.547" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085caa80&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.548" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085cacc0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.549" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085caf00&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.550" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085cb140&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.551" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca750&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20250123 15:27:49.541" endtime="20250123 15:27:49.554"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:49.503" endtime="20250123 15:27:49.554"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:49.327" endtime="20250123 15:27:49.555">Several failures occurred:

1) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/url (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1083666c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

2) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae360&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

3) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af770&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

4) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108...
    [ Message content over the limit has been removed. ]

6) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574110&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

7) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577590&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

8) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9b20&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

9) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca750&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<doc>This scenario to test user can access design page from header</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:31.018" endtime="20250123 15:27:49.555">Setup failed:
Execution terminated by signal

Also teardown failed:
Several failures occurred:

1) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/url (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1083666c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

2) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae360&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

3) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af770&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

4) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108...
    [ Message content over the limit has been removed. ]

6) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574110&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

7) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577590&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

8) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9b20&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

9) MaxRetryError: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/elements (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca750&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</test>
<test id="s1-t2" name="verify user can access katalog page from header" line="16">
<doc>This scenario to test user can access katalog page from header</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.570" endtime="20250123 15:27:49.571">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t3" name="verify user can access tentang kardoos page from header" line="21">
<doc>This scenario to test user can access tentang kardoos page from header</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.572" endtime="20250123 15:27:49.573">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t4" name="verify user can access faqs page from header" line="26">
<doc>This scenario to test user can access faqs page from header</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.573" endtime="20250123 15:27:49.573">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t5" name="verify user can access tentang kardoos page from footer" line="31">
<doc>This scenario to test user can access tentang kardoos page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.574" endtime="20250123 15:27:49.574">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t6" name="verify user can access material &amp; proses page from footer" line="36">
<doc>This scenario to test user can access material &amp; proses page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.575" endtime="20250123 15:27:49.575">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t7" name="verify user can access inspirasi page from footer" line="41">
<doc>This scenario to test user can access inspirasi page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.575" endtime="20250123 15:27:49.576">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t8" name="verify user can access blog page from footer" line="46">
<doc>This scenario to test user can access blog list page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.577" endtime="20250123 15:27:49.577">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t9" name="verify user can access kardoos instant page from footer" line="51">
<doc>This scenario to test user can access kardoos instant page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.578" endtime="20250123 15:27:49.578">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t10" name="verify user can acess design page from footer" line="56">
<doc>This scenario to test user can access design page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.579" endtime="20250123 15:27:49.579">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t11" name="verify user can access instant template page from footer" line="61">
<doc>This scenario to test user can access instant template page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.579" endtime="20250123 15:27:49.580">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t12" name="verify user can access marketplace page from footer" line="66">
<doc>This scenario to test user can access marketplace page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.580" endtime="20250123 15:27:49.581">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t13" name="verify user can access cari supplier page from footer" line="71">
<doc>This scenario to test user can access cari supplier page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.581" endtime="20250123 15:27:49.582">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t14" name="verify user can access syarat &amp; ketentuan page from footer" line="76">
<doc>This scenario to test user can access syarat &amp; ketentuan page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.582" endtime="20250123 15:27:49.583">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t15" name="verify user can access kebijakan privasi page from footer" line="81">
<doc>This scenario to test user can access kebijakan privasi page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.591" endtime="20250123 15:27:49.592">Test execution stopped due to a fatal error.</status>
</test>
<test id="s1-t16" name="verify user can access faqs page from footer" line="86">
<doc>This scenario to test user can access faqs page from footer</doc>
<tag>dev</tag>
<tag>home</tag>
<tag>positive</tag>
<tag>production</tag>
<tag>robot:exit</tag>
<tag>staging</tag>
<status status="FAIL" starttime="20250123 15:27:49.593" endtime="20250123 15:27:49.593">Test execution stopped due to a fatal error.</status>
</test>
<kw name="End Web Test" library="dev" type="TEARDOWN">
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<msg timestamp="20250123 15:27:49.596" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085f92b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5</msg>
<msg timestamp="20250123 15:27:49.597" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085f9670&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5</msg>
<msg timestamp="20250123 15:27:49.598" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085f9d00&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5</msg>
<status status="PASS" starttime="20250123 15:27:49.594" endtime="20250123 15:27:49.624"/>
</kw>
<status status="PASS" starttime="20250123 15:27:49.594" endtime="20250123 15:27:49.624"/>
</kw>
<status status="FAIL" starttime="20250123 15:27:25.947" endtime="20250123 15:27:49.624"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="16" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0" info="combined" combined="NOT robot:exit">NOT robot:exit</stat>
<stat pass="0" fail="16" skip="0">dev</stat>
<stat pass="0" fail="16" skip="0">home</stat>
<stat pass="0" fail="16" skip="0">positive</stat>
<stat pass="0" fail="16" skip="0">production</stat>
<stat pass="0" fail="16" skip="0">staging</stat>
</tag>
<suite>
<stat pass="0" fail="16" skip="0" id="s1" name="HomeSuite">HomeSuite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20250123 15:27:49.314" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectionResetError(54, 'Connection reset by peer')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.318" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ace60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.322" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084acbf0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.324" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ac920&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.332" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084adf40&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/url</msg>
<msg timestamp="20250123 15:27:49.334" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845fad0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/url</msg>
<msg timestamp="20250123 15:27:49.337" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845ffe0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/url</msg>
<msg timestamp="20250123 15:27:49.342" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1083f70b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.345" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1082184d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.349" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845f0e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.357" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10845fbc0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.388" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084acb60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh</msg>
<msg timestamp="20250123 15:27:49.389" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084acd10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh</msg>
<msg timestamp="20250123 15:27:49.390" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ac6e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/refresh</msg>
<msg timestamp="20250123 15:27:49.392" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae660&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.393" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ae870&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.395" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084aea80&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.397" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1082184d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.404" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af3e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.406" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084aeea0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.407" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084af170&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.410" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afa40&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.411" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afc50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.412" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afe60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.413" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085740b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.442" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574950&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.444" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574290&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.445" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084afb90&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.447" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1080e20f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.448" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085740b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.449" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574530&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.451" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085749e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.459" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.461" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575580&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.462" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108575880&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.464" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085761b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.465" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085763f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.467" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576630&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.468" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1082184d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.475" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085771d0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.477" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084ac920&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.478" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108574b00&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.480" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576d50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.481" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085773e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.482" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577620&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.483" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577860&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.490" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c8080&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.491" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1084aee10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.492" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085777a0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.495" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576900&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.496" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c8260&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.497" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c84a0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.498" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c86e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.505" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c97c0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.506" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9550&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.508" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9280&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.510" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9e50&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.536" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577ec0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.537" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108577b60&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.538" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x108576900&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.543" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca3f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.544" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085ca270&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.545" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085c9f10&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/elements</msg>
<msg timestamp="20250123 15:27:49.547" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085caa80&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.548" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085cacc0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.549" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085caf00&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot</msg>
<msg timestamp="20250123 15:27:49.550" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: HTTPConnectionPool(host='localhost', port=55454): Max retries exceeded with url: /session/92fc5a16ba5bdb7d18a1466785767fb5/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085cb140&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20250123 15:27:49.596" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085f92b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5</msg>
<msg timestamp="20250123 15:27:49.597" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085f9670&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5</msg>
<msg timestamp="20250123 15:27:49.598" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x1085f9d00&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/92fc5a16ba5bdb7d18a1466785767fb5</msg>
</errors>
</robot>
